
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  
  build:
  
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4
      - name: build image
        run: docker build -t moladevops237/portfolio .
      - name: push image
        run: |
          docker login -u moladevops237 -p ${{ secrets.REGISTRY_PASSWORD }}
          docker push moladevops237/portfolio
